-- =============================================================================
-- Re-anclaje de la frescura del catálogo de demo · día 12
-- =============================================================================
-- `Plan §5`, día 12: *"Curación del catálogo hacia el guion"*.
--
-- EL PROBLEMA, MEDIDO Y NO SUPUESTO (F-094). El catálogo se sembró el 7-ago con
-- fechas RELATIVAS —`now() - interval 'N days'`, que fue la decisión correcta— y
-- desde entonces no se ha vuelto a sembrar. La base no envejece la siembra: la
-- envejece el calendario. El 14-ago, 220 de las 221 líneas ya pasaban de 7 días
-- y las 14 de `6205-2RS` también, la más fresca por 8. `ResultsTable.tsx:168`
-- pinta en naranja todo lo que pase de 7, así que la columna Antigüedad de
-- SRCH-01 —la pantalla núcleo— saldría ENTERA en naranja delante del socio, y un
-- indicador que marca el 100% de las filas no indica nada.
--
-- El guion lo diseñó al revés (`guion-demo-y-siembra.md` §2.1): *"al menos dos
-- líneas con más de 7 días, y una de más de 30"*. Naranja como EXCEPCIÓN.
--
-- QUÉ HACE. Desplaza `last_upload_at` de todas las líneas por un delta CONSTANTE,
-- el que devuelve la línea más reciente a `now()`. Un desplazamiento constante
-- conserva la distribución relativa entera: la de 34 días de diseño sigue a 34,
-- el orden entre líneas no cambia y la de más de 30 —la que pinta en rojo— sigue
-- estando. No reescribe datos: los mueve en bloque.
--
-- POR QUÉ NO SE RE-SIEMBRA. Las tarjetas CONSULTA de los días 10 y 11 apuntan a
-- `inventory_lines.id` concretos; borrar y volver a insertar las dejaría
-- huérfanas y se llevaría por delante la demostración de "Consultar
-- Seleccionados". Decidido con el PO el 14-ago.
--
-- CUÁNDO SE CORRE. Antes de cada ensayo de `Plan §10` y antes de la reunión del
-- 20-ago. Es idempotente dentro del mismo día: si el desfase es menor de 12
-- horas no toca nada.
--
-- SE VERIFICA A SÍ MISMO, Y ESO NO ES CELO. Un script de curación que no
-- comprueba su resultado es exactamente F-089 otra vez —afirmar un estado de la
-- base sin consultarlo—. Si tras el desplazamiento la distribución no cumple el
-- guion, esto FALLA en voz alta en vez de dejar la demo rota y callada. El caso
-- concreto que atrapa: alguien sube una línea nueva justo antes de correrlo, el
-- delta sale ~0, el desplazamiento no ocurre y sin esta comprobación el script
-- diría "hecho" sin haber hecho nada.
--
-- No lleva metacomandos de psql a propósito: así corre tal cual por `psql`, por
-- el editor SQL de Supabase y por `execute_sql` del MCP.
--
-- ⚠ EL CUERPO SE MUDÓ A `public.demo_reanchor_freshness()` EL DÍA 13, Y ESTO
-- PASÓ A SER UNA LLAMADA. Motivo: el reseteo del entorno de demo
-- (`app/scripts/demo-reset.mjs`) corre desde Node con `supabase-js`, que **no
-- ejecuta SQL suelto** — solo tablas y RPC. Con el algoritmo aquí dentro habría
-- hecho falta reimplementarlo en JavaScript, y entonces existirían dos
-- definiciones del mismo contrato divergiendo en silencio. Este repo tiene tres
-- hallazgos que son esa misma forma (F-012, F-089, F-095).
--
-- Los umbrales, el porqué de cada uno y la verificación siguen siendo los del
-- día 12, palabra por palabra: están en `supabase/migrations/0015_demo_reset_helpers.sql`.
-- Lo único que cambia es que la función **devuelve** el recuento además de
-- lanzar si no cumple, porque un `raise notice` no llega hasta `supabase-js`.
--
-- Se sigue corriendo igual y sigue fallando en voz alta igual.
-- =============================================================================

select public.demo_reanchor_freshness() as resultado;
